// Comprehensive CNAE List for NR-4 Risk Degree
// Format: Class level (5 digits) as per NR-4 Quadro I
export const CNAE_DB = [
    // A - AGRICULTURA, PECUÁRIA, PRODUÇÃO FLORESTAL, PESCA E AQÜICULTURA
    { code: '01.11-3', desc: 'Cultivo de cereais', risk: '3' },
    { code: '01.12-1', desc: 'Cultivo de algodão herbáceo e de outras fibras de lavoura temporária', risk: '3' },
    { code: '01.13-0', desc: 'Cultivo de cana-de-açúcar', risk: '3' },
    { code: '01.14-8', desc: 'Cultivo de fumo', risk: '3' },
    { code: '01.15-6', desc: 'Cultivo de soja', risk: '3' },
    { code: '01.19-9', desc: 'Cultivo de plantas de lavoura temporária não especificadas anteriormente', risk: '3' },
    { code: '01.21-1', desc: 'Horticultura', risk: '3' },
    { code: '01.22-9', desc: 'Cultivo de flores e plantas ornamentais', risk: '3' },
    { code: '01.31-8', desc: 'Cultivo de laranja', risk: '3' },
    { code: '01.32-6', desc: 'Cultivo de uva', risk: '3' },
    { code: '01.33-4', desc: 'Cultivo de cacau, café e chá', risk: '3' },
    { code: '01.34-2', desc: 'Cultivo de café', risk: '3' },
    { code: '01.39-3', desc: 'Cultivo de plantas de lavoura permanente não especificadas anteriormente', risk: '3' },
    { code: '01.41-5', desc: 'Produção de sementes certificadas', risk: '3' },
    { code: '01.42-3', desc: 'Produção de mudas e outras formas de propagação vegetal, certificadas', risk: '3' },
    { code: '01.51-2', desc: 'Criação de bovinos', risk: '3' },
    { code: '01.52-1', desc: 'Criação de outros animais de grande porte', risk: '3' },
    { code: '01.53-9', desc: 'Criação de caprinos e ovinos', risk: '3' },
    { code: '01.54-7', desc: 'Criação de suínos', risk: '3' },
    { code: '01.55-5', desc: 'Criação de aves', risk: '3' },
    { code: '01.59-8', desc: 'Criação de animais não especificados anteriormente', risk: '3' },
    { code: '01.61-0', desc: 'Atividades de apoio à agricultura', risk: '3' },
    { code: '01.62-8', desc: 'Atividades de apoio à pecuária', risk: '3' },
    { code: '01.70-9', desc: 'Caça e serviços relacionados', risk: '3' },
    { code: '02.10-1', desc: 'Produção florestal - florestas plantadas', risk: '4' },
    { code: '02.20-9', desc: 'Produção florestal - florestas nativas', risk: '4' },
    { code: '02.30-6', desc: 'Atividades de apoio à produção florestal', risk: '4' },
    { code: '03.11-6', desc: 'Pesca em água salgada', risk: '3' },
    { code: '03.12-4', desc: 'Pesca em água doce', risk: '3' },
    { code: '03.21-3', desc: 'Aqüicultura em água salgada e salobra', risk: '3' },
    { code: '03.22-1', desc: 'Aqüicultura em água doce', risk: '3' },

    // B - INDÚSTRIAS EXTRATIVAS
    { code: '05.00-3', desc: 'Extração de carvão mineral', risk: '4' },
    { code: '06.00-0', desc: 'Extração de petróleo e gás natural', risk: '4' },
    { code: '07.10-3', desc: 'Extração de minério de ferro', risk: '4' },
    { code: '07.21-9', desc: 'Extração de minério de alumínio', risk: '4' },
    { code: '07.22-7', desc: 'Extração de minério de estanho', risk: '4' },
    { code: '07.23-5', desc: 'Extração de minério de manganês', risk: '4' },
    { code: '07.24-3', desc: 'Extração de minério de metais preciosos', risk: '4' },
    { code: '07.29-4', desc: 'Extração de minerais metálicos não-ferrosos não especificados anteriormente', risk: '4' },
    { code: '08.10-0', desc: 'Extração de pedra, areia e argila', risk: '4' },
    { code: '08.91-6', desc: 'Extração de minerais para fabricação de adubos, fertilizantes e outros produtos químicos', risk: '4' },
    { code: '08.92-4', desc: 'Extração e refino de sal marinho e sal-gema', risk: '4' },
    { code: '08.93-2', desc: 'Extração de gemas (pedras preciosas e semipreciosas)', risk: '4' },
    { code: '08.99-1', desc: 'Extração de minerais não-metálicos não especificados anteriormente', risk: '4' },
    { code: '09.10-6', desc: 'Atividades de apoio à extração de petróleo e gás natural', risk: '4' },
    { code: '09.90-4', desc: 'Atividades de apoio à extração de minerais, exceto petróleo e gás natural', risk: '4' },

    // C - INDÚSTRIAS DE TRANSFORMAÇÃO
    { code: '10.11-2', desc: 'Abate de reses, exceto suínos', risk: '3' },
    { code: '10.12-1', desc: 'Abate de suínos, aves e outros pequenos animais', risk: '3' },
    { code: '10.13-9', desc: 'Fabricação de produtos de carne', risk: '3' },
    { code: '10.20-1', desc: 'Preservação do pescado e fabricação de produtos do pescado', risk: '3' },
    { code: '10.31-7', desc: 'Fabricação de conservas de frutas', risk: '3' },
    { code: '10.32-5', desc: 'Fabricação de conservas de legumes e outros vegetais', risk: '3' },
    { code: '10.33-3', desc: 'Fabricação de sucos de frutas, hortaliças e legumes', risk: '3' },
    { code: '10.41-4', desc: 'Fabricação de óleos vegetais em bruto, exceto óleo de milho', risk: '3' },
    { code: '10.42-2', desc: 'Fabricação de óleos vegetais refinados, exceto óleo de milho', risk: '3' },
    { code: '10.43-1', desc: 'Fabricação de margarina e outras gorduras vegetais e de óleos não-comestíveis de animais', risk: '3' },
    { code: '10.51-1', desc: 'Laticínios', risk: '3' },
    { code: '10.52-0', desc: 'Fabricação de laticínios', risk: '3' },
    { code: '10.53-8', desc: 'Fabricação de sorvetes e outros gelados comestíveis', risk: '3' },
    { code: '10.61-9', desc: 'Beneficiamento de arroz e fabricação de produtos do arroz', risk: '3' },
    { code: '10.62-7', desc: 'Moagem de trigo e fabricação de derivados', risk: '3' },
    { code: '10.63-5', desc: 'Fabricação de farinha de mandioca e derivados', risk: '2' },
    { code: '10.64-3', desc: 'Fabricação de farinha de milho e derivados', risk: '2' },
    { code: '10.65-1', desc: 'Fabricação de amidos e féculas de vegetais', risk: '2' },
    { code: '10.66-0', desc: 'Fabricação de alimentos para animais', risk: '3' },
    { code: '10.69-4', desc: 'Moagem e fabricação de produtos de origem vegetal não especificados anteriormente', risk: '2' },
    { code: '10.71-6', desc: 'Fabricação de açúcar em bruto', risk: '3' },
    { code: '10.72-4', desc: 'Fabricação de açúcar refinado', risk: '3' },
    { code: '10.81-3', desc: 'Torrefação e moagem de café', risk: '2' },
    { code: '10.82-1', desc: 'Fabricação de produtos à base de café', risk: '2' },
    { code: '10.91-1', desc: 'Fabricação de produtos de panificação', risk: '2' },
    { code: '10.92-9', desc: 'Fabricação de biscoitos e bolachas', risk: '2' },
    { code: '10.93-7', desc: 'Fabricação de produtos derivados do cacau e de chocolates', risk: '2' },
    { code: '10.94-5', desc: 'Fabricação de massas alimentícias', risk: '2' },
    { code: '10.95-3', desc: 'Fabricação de especiarias, molhos, temperos e condimentos', risk: '2' },
    { code: '10.96-1', desc: 'Fabricação de alimentos e pratos prontos', risk: '2' },
    { code: '10.99-6', desc: 'Fabricação de produtos alimentícios não especificados anteriormente', risk: '2' },
    { code: '11.11-9', desc: 'Fabricação de aguardentes e outras bebidas destiladas', risk: '3' },
    { code: '11.12-7', desc: 'Fabricação de vinho', risk: '3' },
    { code: '11.13-5', desc: 'Fabricação de malte, cervejas e chopes', risk: '3' },
    { code: '11.21-6', desc: 'Fabricação de águas envasadas', risk: '3' },
    { code: '11.22-4', desc: 'Fabricação de refrigerantes e de outras bebidas não-alcoólicas', risk: '3' },
    { code: '12.10-7', desc: 'Processamento industrial do fumo', risk: '3' },
    { code: '12.20-4', desc: 'Fabricação de produtos do fumo', risk: '3' },
    { code: '13.11-1', desc: 'Preparação e fiação de fibras de algodão', risk: '3' },
    { code: '13.12-0', desc: 'Preparação e fiação de fibras têxteis naturais, exceto algodão', risk: '3' },
    { code: '13.13-8', desc: 'Fiação de fibras artificiais e sintéticas', risk: '3' },
    { code: '13.14-6', desc: 'Fabricação de linhas para costurar e bordar', risk: '3' },
    { code: '13.21-9', desc: 'Tecelagem de fios de algodão', risk: '3' },
    { code: '13.22-7', desc: 'Tecelagem de fios de fibras têxteis naturais, exceto algodão', risk: '3' },
    { code: '13.23-5', desc: 'Tecelagem de fios de fibras artificiais e sintéticas', risk: '3' },
    { code: '13.30-8', desc: 'Fabricação de tecidos de malha', risk: '3' },
    { code: '13.40-5', desc: 'Acabamentos em fios, tecidos e artefatos têxteis', risk: '3' },
    { code: '13.51-1', desc: 'Fabricação de artefatos têxteis para uso doméstico', risk: '2' },
    { code: '13.52-9', desc: 'Fabricação de artefatos de tapeçaria', risk: '2' },
    { code: '13.53-7', desc: 'Fabricação de artefatos de cordoaria', risk: '2' },
    { code: '13.59-6', desc: 'Fabricação de outros produtos têxteis não especificados anteriormente', risk: '2' },
    { code: '14.11-8', desc: 'Confecção de roupas íntimas', risk: '2' },
    { code: '14.12-6', desc: 'Confecção de peças do vestuário, exceto roupas íntimas', risk: '2' },
    { code: '14.13-4', desc: 'Confecção de roupas profissionais', risk: '2' },
    { code: '14.14-2', desc: 'Fabricação de acessórios do vestuário, exceto para segurança e proteção', risk: '2' },
    { code: '14.21-5', desc: 'Fabricação de meias', risk: '2' },
    { code: '14.22-3', desc: 'Fabricação de artigos do vestuário, produzidos em malharias e tricotagens, exceto meias', risk: '2' },
    { code: '15.10-6', desc: 'Curtimento e outras preparações de couro', risk: '3' },
    { code: '15.21-1', desc: 'Fabricação de artigos para viagem, bolsas e semelhantes de qualquer material', risk: '2' },
    { code: '15.29-7', desc: 'Fabricação de artefatos de couro não especificados anteriormente', risk: '2' },
    { code: '15.31-9', desc: 'Fabricação de calçados de couro', risk: '3' },
    { code: '15.32-7', desc: 'Fabricação de tênis de qualquer material', risk: '3' },
    { code: '15.33-5', desc: 'Fabricação de calçados de material sintético', risk: '3' },
    { code: '15.39-4', desc: 'Fabricação de calçados de materiais não especificados anteriormente', risk: '3' },
    { code: '15.40-8', desc: 'Fabricação de partes para calçados, de qualquer material', risk: '3' },
    { code: '16.10-2', desc: 'Desdobramento de madeira', risk: '4' },
    { code: '16.21-8', desc: 'Fabricação de madeira laminada e de chapas de madeira compensada, prensada e aglomerada', risk: '3' },
    { code: '16.22-6', desc: 'Fabricação de estruturas de madeira e de artigos de carpintaria para construção', risk: '3' },
    { code: '16.23-4', desc: 'Fabricação de artefatos de tanoaria e de embalagens de madeira', risk: '3' },
    { code: '16.29-3', desc: 'Fabricação de artefatos de madeira, palha, cortiça, vime e material trançado não especificados anteriormente, exceto móveis', risk: '3' },
    { code: '17.10-9', desc: 'Fabricação de celulose e outras pastas para a fabricação de papel', risk: '3' },
    { code: '17.21-4', desc: 'Fabricação de papel', risk: '3' },
    { code: '17.22-2', desc: 'Fabricação de cartolina e papel-cartão', risk: '3' },
    { code: '17.31-1', desc: 'Fabricação de embalagens de papel', risk: '2' },
    { code: '17.32-0', desc: 'Fabricação de embalagens de cartolina e papel-cartão', risk: '2' },
    { code: '17.33-8', desc: 'Fabricação de chapas e de embalagens de papelão ondulado', risk: '2' },
    { code: '17.41-9', desc: 'Fabricação de produtos de papel, cartolina, papel-cartão e papelão ondulado para uso comercial e de escritório', risk: '2' },
    { code: '17.42-7', desc: 'Fabricação de produtos de papel para uso doméstico e higiênico-sanitário', risk: '2' },
    { code: '17.49-4', desc: 'Fabricação de produtos de pastas celulósicas, papel, cartolina, papel-cartão e papelão ondulado não especificados anteriormente', risk: '2' },
    { code: '18.11-3', desc: 'Impressão de jornais', risk: '3' },
    { code: '18.12-1', desc: 'Impressão de material de segurança', risk: '3' },
    { code: '18.13-0', desc: 'Impressão de materiais para outros usos', risk: '3' },
    { code: '18.21-1', desc: 'Serviços de pré-impressão', risk: '3' },
    { code: '18.22-9', desc: 'Serviços de acabamentos gráficos', risk: '3' },
    { code: '18.30-0', desc: 'Reprodução de som e vídeo em qualquer suporte', risk: '2' },
    { code: '19.10-1', desc: 'Coquerias', risk: '4' },
    { code: '19.21-7', desc: 'Fabricação de produtos do refino de petróleo', risk: '3' },
    { code: '19.22-5', desc: 'Fabricação de produtos derivados do petróleo, exceto produtos do refino', risk: '3' },
    { code: '19.31-4', desc: 'Fabricação de álcool', risk: '3' },
    { code: '19.32-2', desc: 'Fabricação de biocombustíveis, exceto álcool', risk: '3' },
    { code: '20.11-8', desc: 'Fabricação de cloro e álcalis', risk: '3' },
    { code: '20.12-6', desc: 'Fabricação de intermediários para fertilizantes', risk: '3' },
    { code: '20.13-4', desc: 'Fabricação de adubos e fertilizantes', risk: '3' },
    { code: '20.14-2', desc: 'Fabricação de gases industriais', risk: '3' },
    { code: '20.19-3', desc: 'Fabricação de produtos químicos inorgânicos não especificados anteriormente', risk: '3' },
    { code: '20.21-5', desc: 'Fabricação de produtos petroquímicos básicos', risk: '3' },
    { code: '20.22-3', desc: 'Fabricação de intermediários para plastificantes, resinas e fibras', risk: '3' },
    { code: '20.29-1', desc: 'Fabricação de produtos químicos orgânicos não especificados anteriormente', risk: '3' },
    { code: '20.31-2', desc: 'Fabricação de resinas termoplásticas', risk: '3' },
    { code: '20.32-1', desc: 'Fabricação de resinas termofixas', risk: '3' },
    { code: '20.33-9', desc: 'Fabricação de elastômeros', risk: '3' },
    { code: '20.40-1', desc: 'Fabricação de fibras artificiais e sintéticas', risk: '3' },
    { code: '20.51-7', desc: 'Fabricação de defensivos agrícolas', risk: '3' },
    { code: '20.52-5', desc: 'Fabricação de desinfestantes domissanitários', risk: '3' },
    { code: '20.61-4', desc: 'Fabricação de sabões e detergentes sintéticos', risk: '3' },
    { code: '20.62-2', desc: 'Fabricação de produtos de limpeza e polimento', risk: '3' },
    { code: '20.63-1', desc: 'Fabricação de cosméticos, produtos de perfumaria e de higiene pessoal', risk: '2' },
    { code: '20.71-1', desc: 'Fabricação de tintas, vernizes, esmaltes e lacas', risk: '3' },
    { code: '20.72-0', desc: 'Fabricação de tintas de impressão', risk: '3' },
    { code: '20.73-8', desc: 'Fabricação de impermeabilizantes, solventes e produtos afins', risk: '3' },
    { code: '20.91-6', desc: 'Fabricação de adesivos e selantes', risk: '3' },
    { code: '20.92-4', desc: 'Fabricação de explosivos', risk: '4' },
    { code: '20.93-2', desc: 'Fabricação de aditivos de uso industrial', risk: '3' },
    { code: '20.94-1', desc: 'Fabricação de catalisadores', risk: '3' },
    { code: '20.99-1', desc: 'Fabricação de produtos químicos não especificados anteriormente', risk: '3' },
    { code: '21.10-6', desc: 'Fabricação de produtos farmoquímicos', risk: '3' },
    { code: '21.21-1', desc: 'Fabricação de medicamentos para uso humano', risk: '3' },
    { code: '21.22-0', desc: 'Fabricação de medicamentos para uso veterinário', risk: '3' },
    { code: '21.23-8', desc: 'Fabricação de preparações farmacêuticas', risk: '3' },
    { code: '22.11-1', desc: 'Fabricação de pneumáticos e de câmaras-de-ar', risk: '3' },
    { code: '22.12-9', desc: 'Reforma de pneumáticos usados', risk: '3' },
    { code: '22.19-6', desc: 'Fabricação de artefatos de borracha não especificados anteriormente', risk: '3' },
    { code: '22.21-8', desc: 'Fabricação de laminados planos e tubulares de material plástico', risk: '3' },
    { code: '22.22-6', desc: 'Fabricação de embalagens de material plástico', risk: '3' },
    { code: '22.23-4', desc: 'Fabricação de tubos e acessórios de material plástico para uso na construção', risk: '3' },
    { code: '22.29-3', desc: 'Fabricação de artefatos de material plástico não especificados anteriormente', risk: '3' },
    { code: '23.11-7', desc: 'Fabricação de vidro plano e de segurança', risk: '3' },
    { code: '23.12-5', desc: 'Fabricação de embalagens de vidro', risk: '3' },
    { code: '23.19-2', desc: 'Fabricação de artigos de vidro', risk: '3' },
    { code: '23.20-6', desc: 'Fabricação de cimento', risk: '4' },
    { code: '23.30-3', desc: 'Fabricação de artefatos de concreto, cimento, fibrocimento, gesso e materiais semelhantes', risk: '3' },
    { code: '23.41-9', desc: 'Fabricação de produtos cerâmicos refratários', risk: '3' },
    { code: '23.42-7', desc: 'Fabricação de produtos cerâmicos não-refratários para uso estrutural na construção', risk: '3' },
    { code: '23.49-4', desc: 'Fabricação de produtos cerâmicos não-refratários não especificados anteriormente', risk: '3' },
    { code: '23.91-5', desc: 'Aparelhamento e outros trabalhos em pedras', risk: '3' },
    { code: '23.92-3', desc: 'Fabricação de cal e gesso', risk: '4' },
    { code: '23.99-1', desc: 'Fabricação de produtos de minerais não-metálicos não especificados anteriormente', risk: '3' },
    { code: '24.11-3', desc: 'Produção de ferro-gusa', risk: '4' },
    { code: '24.12-1', desc: 'Produção de ferroligas', risk: '4' },
    { code: '24.21-1', desc: 'Produção de semi-acabados de aço', risk: '4' },
    { code: '24.22-9', desc: 'Produção de laminados planos de aço', risk: '4' },
    { code: '24.23-7', desc: 'Produção de laminados longos de aço', risk: '4' },
    { code: '24.24-5', desc: 'Produção de relaminados, trefilados e perfilados de aço', risk: '4' },
    { code: '24.31-8', desc: 'Produção de tubos de aço com costura', risk: '4' },
    { code: '24.39-3', desc: 'Produção de outros tubos de ferro e aço', risk: '4' },
    { code: '24.41-5', desc: 'Metalurgia do alumínio e suas ligas', risk: '4' },
    { code: '24.42-3', desc: 'Metalurgia dos metais preciosos', risk: '4' },
    { code: '24.43-1', desc: 'Metalurgia do cobre', risk: '4' },
    { code: '24.49-1', desc: 'Metalurgia dos metais não-ferrosos e suas ligas não especificados anteriormente', risk: '4' },
    { code: '24.51-2', desc: 'Fundição de ferro e aço', risk: '4' },
    { code: '24.52-1', desc: 'Fundição de metais não-ferrosos e suas ligas', risk: '4' },
    { code: '25.11-0', desc: 'Fabricação de estruturas metálicas', risk: '3' },
    { code: '25.12-8', desc: 'Fabricação de esquadrias de metal', risk: '3' },
    { code: '25.13-6', desc: 'Fabricação de obras de caldeiraria pesada', risk: '3' },
    { code: '25.21-7', desc: 'Fabricação de tanques, reservatórios metálicos e caldeiras para aquecimento central', risk: '3' },
    { code: '25.22-5', desc: 'Fabricação de caldeiras geradoras de vapor, exceto para aquecimento central e para veículos', risk: '3' },
    { code: '25.31-4', desc: 'Produção de forjados de aço e de metais não-ferrosos e suas ligas', risk: '3' },
    { code: '25.32-2', desc: 'Produção de artefatos estampados de metal', risk: '3' },
    { code: '25.39-0', desc: 'Serviços de usinagem, solda, tratamento e revestimento em metais', risk: '3' },
    { code: '25.41-1', desc: 'Fabricação de artigos de cutelaria', risk: '3' },
    { code: '25.42-0', desc: 'Fabricação de artigos de serralheria, exceto esquadrias', risk: '3' },
    { code: '25.43-8', desc: 'Fabricação de ferramentas', risk: '3' },
    { code: '25.50-1', desc: 'Fabricação de equipamento bélico pesado, armas de fogo e munições', risk: '4' },
    { code: '25.91-8', desc: 'Fabricação de embalagens metálicas', risk: '3' },
    { code: '25.92-6', desc: 'Fabricação de produtos de trefilados de metal', risk: '3' },
    { code: '25.93-4', desc: 'Fabricação de artigos de metal para uso doméstico e pessoal', risk: '3' },
    { code: '25.99-3', desc: 'Fabricação de produtos de metal não especificados anteriormente', risk: '3' },
    { code: '26.10-8', desc: 'Fabricação de componentes eletrônicos', risk: '3' },
    { code: '26.21-3', desc: 'Fabricação de equipamentos de informática', risk: '3' },
    { code: '26.22-1', desc: 'Fabricação de periféricos para equipamentos de informática', risk: '3' },
    { code: '26.31-1', desc: 'Fabricação de equipamentos transmissores de comunicação', risk: '3' },
    { code: '26.32-9', desc: 'Fabricação de aparelhos telefônicos e de outros equipamentos de comunicação', risk: '3' },
    { code: '26.40-0', desc: 'Fabricação de aparelhos de recepção, reprodução, gravação e amplificação de áudio e vídeo', risk: '3' },
    { code: '26.51-5', desc: 'Fabricação de aparelhos e equipamentos de medida, teste e controle', risk: '3' },
    { code: '26.52-3', desc: 'Fabricação de cronômetros e relógios', risk: '3' },
    { code: '26.60-4', desc: 'Fabricação de aparelhos eletromédicos e eletroterapêuticos e equipamentos de irradiação', risk: '3' },
    { code: '26.70-1', desc: 'Fabricação de equipamentos e instrumentos ópticos, fotográficos e cinematográficos', risk: '3' },
    { code: '26.80-9', desc: 'Fabricação de mídias virgens, magnéticas e ópticas', risk: '3' },
    { code: '27.10-4', desc: 'Fabricação de geradores, transformadores e motores elétricos', risk: '3' },
    { code: '27.21-0', desc: 'Fabricação de pilhas, baterias e acumuladores elétricos, exceto para veículos automotores', risk: '3' },
    { code: '27.22-8', desc: 'Fabricação de baterias e acumuladores para veículos automotores', risk: '3' },
    { code: '27.31-7', desc: 'Fabricação de aparelhos e equipamentos para distribuição e controle de energia elétrica', risk: '3' },
    { code: '27.32-5', desc: 'Fabricação de material elétrico para instalações em circuito de consumo', risk: '3' },
    { code: '27.33-3', desc: 'Fabricação de fios, cabos e condutores elétricos isolados', risk: '3' },
    { code: '27.40-6', desc: 'Fabricação de lâmpadas e outros equipamentos de iluminação', risk: '3' },
    { code: '27.51-1', desc: 'Fabricação de fogões, refrigeradores e máquinas de lavar e secar para uso doméstico', risk: '3' },
    { code: '27.59-7', desc: 'Fabricação de aparelhos eletrodomésticos não especificados anteriormente', risk: '3' },
    { code: '27.90-2', desc: 'Fabricação de equipamentos e aparelhos elétricos não especificados anteriormente', risk: '3' },
    { code: '28.11-9', desc: 'Fabricação de motores e turbinas, exceto para aviões e veículos rodoviários', risk: '3' },
    { code: '28.12-7', desc: 'Fabricação de equipamentos hidráulicos e pneumáticos, exceto válvulas', risk: '3' },
    { code: '28.13-5', desc: 'Fabricação de válvulas, registros e torneiras', risk: '3' },
    { code: '28.14-3', desc: 'Fabricação de compressores', risk: '3' },
    { code: '28.15-1', desc: 'Fabricação de equipamentos de transmissão para fins industriais', risk: '3' },
    { code: '28.21-6', desc: 'Fabricação de aparelhos e equipamentos para instalações térmicas', risk: '3' },
    { code: '28.22-4', desc: 'Fabricação de máquinas, equipamentos e aparelhos para transporte e elevação de cargas e pessoas', risk: '3' },
    { code: '28.23-2', desc: 'Fabricação de máquinas e aparelhos de refrigeração e ventilação para uso industrial e comercial', risk: '3' },
    { code: '28.24-1', desc: 'Fabricação de aparelhos e equipamentos de ar condicionado', risk: '3' },
    { code: '28.25-9', desc: 'Fabricação de máquinas e equipamentos para saneamento básico e ambiental', risk: '3' },
    { code: '28.29-1', desc: 'Fabricação de máquinas e equipamentos de uso geral não especificados anteriormente', risk: '3' },
    { code: '28.31-3', desc: 'Fabricação de tratores agrícolas', risk: '3' },
    { code: '28.32-1', desc: 'Fabricação de máquinas e equipamentos para a agricultura e pecuária', risk: '3' },
    { code: '28.33-0', desc: 'Fabricação de máquinas e equipamentos para a prospecção e extração de petróleo', risk: '3' },
    { code: '28.40-2', desc: 'Fabricação de máquinas-ferramenta', risk: '3' },
    { code: '28.51-8', desc: 'Fabricação de máquinas e equipamentos para a prospecção e extração de minerais', risk: '3' },
    { code: '28.52-6', desc: 'Fabricação de outras máquinas e equipamentos para uso na extração mineral', risk: '3' },
    { code: '28.53-4', desc: 'Fabricação de tratores, exceto agrícolas', risk: '3' },
    { code: '28.54-2', desc: 'Fabricação de máquinas e equipamentos para terraplenagem, pavimentação e construção', risk: '3' },
    { code: '28.61-5', desc: 'Fabricação de máquinas para a indústria metalúrgica, exceto máquinas-ferramenta', risk: '3' },
    { code: '28.62-3', desc: 'Fabricação de máquinas e equipamentos para as indústrias de alimentos, bebidas e fumo', risk: '3' },
    { code: '28.63-1', desc: 'Fabricação de máquinas e equipamentos para a indústria têxtil', risk: '3' },
    { code: '28.64-0', desc: 'Fabricação de máquinas e equipamentos para as indústrias do vestuário, do couro e de calçados', risk: '3' },
    { code: '28.65-8', desc: 'Fabricação de máquinas e equipamentos para as indústrias de celulose, papel e papelão e artefatos', risk: '3' },
    { code: '28.66-6', desc: 'Fabricação de máquinas e equipamentos para a indústria do plástico', risk: '3' },
    { code: '28.69-1', desc: 'Fabricação de máquinas e equipamentos para uso industrial específico não especificados anteriormente', risk: '3' },
    { code: '29.10-7', desc: 'Fabricação de automóveis, camionetas e utilitários', risk: '3' },
    { code: '29.20-4', desc: 'Fabricação de caminhões e ônibus', risk: '3' },
    { code: '29.30-1', desc: 'Fabricação de cabines, carrocerias e reboques para veículos automotores', risk: '3' },
    { code: '29.41-7', desc: 'Fabricação de peças e acessórios para o sistema motor de veículos automotores', risk: '3' },
    { code: '29.42-5', desc: 'Fabricação de peças e acessórios para os sistemas de marcha e transmissão de veículos automotores', risk: '3' },
    { code: '29.43-3', desc: 'Fabricação de peças e acessórios para o sistema de freios de veículos automotores', risk: '3' },
    { code: '29.44-1', desc: 'Fabricação de peças e acessórios para o sistema de direção e suspensão de veículos automotores', risk: '3' },
    { code: '29.45-0', desc: 'Fabricação de material elétrico e eletrônico para veículos automotores, exceto baterias', risk: '3' },
    { code: '29.49-2', desc: 'Fabricação de peças e acessórios para veículos automotores não especificados anteriormente', risk: '3' },
    { code: '30.11-3', desc: 'Construção de embarcações e estruturas flutuantes', risk: '3' },
    { code: '30.12-1', desc: 'Construção de embarcações para esporte e lazer', risk: '3' },
    { code: '30.31-8', desc: 'Fabricação de locomotivas, vagões e outros materiais rodantes', risk: '3' },
    { code: '30.32-6', desc: 'Fabricação de peças e acessórios para veículos ferroviários', risk: '3' },
    { code: '30.41-5', desc: 'Fabricação de aeronaves', risk: '3' },
    { code: '30.42-3', desc: 'Fabricação de turbinas, motores e outros componentes e peças para aeronaves', risk: '3' },
    { code: '30.50-4', desc: 'Fabricação de veículos militares de combate', risk: '3' },
    { code: '30.91-1', desc: 'Fabricação de motocicletas', risk: '3' },
    { code: '30.92-0', desc: 'Fabricação de bicicletas e triciclos não-motorizados', risk: '3' },
    { code: '30.99-7', desc: 'Fabricação de equipamentos de transporte não especificados anteriormente', risk: '3' },
    { code: '31.01-2', desc: 'Fabricação de móveis com predominância de madeira', risk: '3' },
    { code: '31.02-1', desc: 'Fabricação de móveis com predominância de metal', risk: '3' },
    { code: '31.03-9', desc: 'Fabricação de móveis de outros materiais', risk: '3' },
    { code: '31.04-7', desc: 'Fabricação de colchões', risk: '2' },
    { code: '32.11-6', desc: 'Lapidação de gemas e fabricação de artefatos de ourivesaria e joalheria', risk: '3' },
    { code: '32.12-4', desc: 'Fabricação de bijuterias e artefatos semelhantes', risk: '3' },
    { code: '32.20-5', desc: 'Fabricação de instrumentos musicais', risk: '3' },
    { code: '32.30-2', desc: 'Fabricação de artefatos para pesca e esporte', risk: '2' },
    { code: '32.40-0', desc: 'Fabricação de brinquedos e jogos recreativos', risk: '3' },
    { code: '32.50-7', desc: 'Fabricação de instrumentos e materiais para uso médico e odontológico e de artigos ópticos', risk: '3' },
    { code: '32.91-4', desc: 'Fabricação de escovas, pincéis e vassouras', risk: '3' },
    { code: '32.92-2', desc: 'Fabricação de equipamentos e acessórios para segurança e proteção pessoal e profissional', risk: '3' },
    { code: '32.99-0', desc: 'Fabricação de produtos diversos não especificados anteriormente', risk: '3' },
    { code: '33.11-2', desc: 'Manutenção e reparação de tanques, reservatórios metálicos e caldeiras, exceto para veículos', risk: '3' },
    { code: '33.12-1', desc: 'Manutenção e reparação de equipamentos eletrônicos e ópticos', risk: '3' },
    { code: '33.13-9', desc: 'Manutenção e reparação de máquinas e equipamentos elétricos', risk: '3' },
    { code: '33.14-7', desc: 'Manutenção e reparação de máquinas e equipamentos da indústria mecânica', risk: '3' },
    { code: '33.15-5', desc: 'Manutenção e reparação de veículos ferroviários', risk: '3' },
    { code: '33.16-3', desc: 'Manutenção e reparação de aeronaves', risk: '3' },
    { code: '33.17-1', desc: 'Manutenção e reparação de embarcações', risk: '3' },
    { code: '33.19-8', desc: 'Manutenção e reparação de equipamentos e produtos não especificados anteriormente', risk: '3' },
    { code: '33.21-0', desc: 'Instalação de máquinas e equipamentos industriais', risk: '3' },
    { code: '35.11-5', desc: 'Geração de energia elétrica', risk: '3' },
    { code: '35.12-3', desc: 'Transmissão de energia elétrica', risk: '3' },
    { code: '35.13-1', desc: 'Comércio atacadista de energia elétrica', risk: '3' },
    { code: '35.14-0', desc: 'Distribuição de energia elétrica', risk: '3' },
    { code: '35.20-4', desc: 'Produção de gás; processamento de gás natural', risk: '3' },
    { code: '35.30-1', desc: 'Produção e distribuição de vapor, água quente e ar condicionado', risk: '3' },
    { code: '36.00-6', desc: 'Captação, tratamento e distribuição de água', risk: '3' },
    { code: '37.01-1', desc: 'Gestão de redes de esgoto', risk: '3' },
    { code: '37.02-9', desc: 'Atividades relacionadas a esgoto, exceto a gestão de redes', risk: '3' },
    { code: '38.11-4', desc: 'Coleta de resíduos não-perigosos', risk: '3' },
    { code: '38.12-2', desc: 'Coleta de resíduos perigosos', risk: '3' },
    { code: '38.21-1', desc: 'Tratamento e disposição de resíduos não-perigosos', risk: '3' },
    { code: '38.22-0', desc: 'Tratamento e disposição de resíduos perigosos', risk: '3' },
    { code: '38.31-9', desc: 'Recuperação de materiais metálicos', risk: '3' },
    { code: '38.32-7', desc: 'Recuperação de materiais plásticos', risk: '3' },
    { code: '38.39-4', desc: 'Recuperação de materiais não especificados anteriormente', risk: '3' },
    { code: '39.00-5', desc: 'Descontaminação e outros serviços de gestão de resíduos', risk: '3' },
    { code: '41.10-7', desc: 'Incorporação de empreendimentos imobiliários', risk: '1' },
    { code: '41.20-4', desc: 'Construção de edifícios', risk: '3' },
    { code: '42.11-1', desc: 'Construção de rodovias e ferrovias', risk: '4' },
    { code: '42.12-0', desc: 'Construção de obras de arte especiais', risk: '4' },
    { code: '42.13-8', desc: 'Obras de urbanização - ruas, praças e calçadas', risk: '3' },
    { code: '42.21-9', desc: 'Obras para geração e distribuição de energia elétrica e para telecomunicações', risk: '4' },
    { code: '42.22-7', desc: 'Construção de redes de abastecimento de água, coleta de esgoto e construções correlatas', risk: '4' },
    { code: '42.23-5', desc: 'Construção de redes de transportes por dutos, exceto para água e esgoto', risk: '4' },
    { code: '42.91-0', desc: 'Obras portuárias, marítimas e fluviais', risk: '4' },
    { code: '42.92-8', desc: 'Montagem de instalações industriais e de estruturas metálicas', risk: '4' },
    { code: '42.99-5', desc: 'Obras de engenharia civil não especificadas anteriormente', risk: '3' },
    { code: '43.11-8', desc: 'Demolição e preparação de canteiros de obras', risk: '4' },
    { code: '43.12-6', desc: 'Perfurações e sondagens', risk: '4' },
    { code: '43.13-4', desc: 'Obras de terraplenagem', risk: '3' },
    { code: '43.19-3', desc: 'Serviços de preparação do terreno não especificados anteriormente', risk: '3' },
    { code: '43.21-5', desc: 'Instalação e manutenção elétrica', risk: '3' },
    { code: '43.22-3', desc: 'Instalações hidráulicas, de sistemas de ventilação e refrigeração', risk: '3' },
    { code: '43.29-1', desc: 'Obras de instalações em construções não especificadas anteriormente', risk: '3' },
    { code: '43.30-4', desc: 'Obras de acabamento', risk: '3' },
    { code: '43.91-6', desc: 'Obras de fundações', risk: '4' },
    { code: '43.99-1', desc: 'Serviços especializados para construção não especificados anteriormente', risk: '3' },
    { code: '45.11-1', desc: 'Comércio a varejo e por atacado de veículos automotores', risk: '2' },
    { code: '45.12-9', desc: 'Comércio sob consignação de veículos automotores', risk: '2' },
    { code: '45.20-0', desc: 'Manutenção e reparação de veículos automotores', risk: '3' },
    { code: '45.30-7', desc: 'Comércio de peças e acessórios para veículos automotores', risk: '2' },
    { code: '45.41-2', desc: 'Comércio por atacado e a varejo de motocicletas, peças e acessórios', risk: '2' },
    { code: '45.42-1', desc: 'Representantes comerciais e agentes do comércio de motocicletas, peças e acessórios', risk: '2' },
    { code: '45.43-9', desc: 'Manutenção e reparação de motocicletas e motonetas', risk: '3' },
    { code: '46.11-7', desc: 'Representantes comerciais e agentes do comércio de matérias-primas agrícolas e animais vivos', risk: '2' },
    { code: '46.21-4', desc: 'Comércio atacadista de café em grão', risk: '2' },
    { code: '46.22-2', desc: 'Comércio atacadista de soja', risk: '2' },
    { code: '46.23-1', desc: 'Comércio atacadista de animais vivos, alimentos para animais e matérias-primas agrícolas', risk: '2' },
    { code: '46.31-1', desc: 'Comércio atacadista de leite e laticínios', risk: '2' },
    { code: '46.32-0', desc: 'Comércio atacadista de cereais e leguminosas beneficiados, farinhas, amidos e féculas', risk: '2' },
    { code: '46.33-8', desc: 'Comércio atacadista de hortifrutigranjeiros', risk: '2' },
    { code: '46.34-6', desc: 'Comércio atacadista de carnes, produtos da carne e pescado', risk: '2' },
    { code: '46.35-4', desc: 'Comércio atacadista de bebidas', risk: '2' },
    { code: '46.36-2', desc: 'Comércio atacadista de produtos do fumo', risk: '2' },
    { code: '46.37-1', desc: 'Comércio atacadista especializado em produtos alimentícios não especificados anteriormente', risk: '2' },
    { code: '46.39-7', desc: 'Comércio atacadista de produtos alimentícios em geral', risk: '2' },
    { code: '46.41-9', desc: 'Comércio atacadista de tecidos, artefatos de tecidos e de armarinho', risk: '2' },
    { code: '46.42-7', desc: 'Comércio atacadista de artigos do vestuário e acessórios', risk: '2' },
    { code: '46.43-5', desc: 'Comércio atacadista de calçados e artigos de viagem', risk: '2' },
    { code: '46.44-3', desc: 'Comércio atacadista de produtos farmacêuticos para uso humano e veterinário', risk: '2' },
    { code: '46.45-1', desc: 'Comércio atacadista de instrumentos e materiais para uso médico, cirúrgico, ortopédico e odontológico', risk: '2' },
    { code: '46.46-0', desc: 'Comércio atacadista de cosméticos, produtos de perfumaria e de higiene pessoal', risk: '2' },
    { code: '46.47-8', desc: 'Comércio atacadista de artigos de escritório e de papelaria', risk: '2' },
    { code: '46.49-4', desc: 'Comércio atacadista de equipamentos e artigos de uso pessoal e doméstico não especificados anteriormente', risk: '2' },
    { code: '46.51-6', desc: 'Comércio atacadista de computadores, periféricos e suprimentos de informática', risk: '2' },
    { code: '46.52-4', desc: 'Comércio atacadista de componentes eletrônicos e equipamentos de telefonia e comunicação', risk: '2' },
    { code: '46.61-3', desc: 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso agropecuário', risk: '2' },
    { code: '46.62-1', desc: 'Comércio atacadista de máquinas, equipamentos para terraplenagem, mineração e construção', risk: '2' },
    { code: '46.63-0', desc: 'Comércio atacadista de máquinas e equipamentos para uso industrial', risk: '2' },
    { code: '46.64-8', desc: 'Comércio atacadista de máquinas, aparelhos e equipamentos para uso odonto-médico-hospitalar', risk: '2' },
    { code: '46.65-6', desc: 'Comércio atacadista de máquinas e equipamentos para uso comercial', risk: '2' },
    { code: '46.69-9', desc: 'Comércio atacadista de máquinas, aparelhos e equipamentos não especificados anteriormente', risk: '2' },
    { code: '46.71-1', desc: 'Comércio atacadista de madeira e produtos derivados', risk: '3' },
    { code: '46.72-9', desc: 'Comércio atacadista de ferragens e ferramentas', risk: '2' },
    { code: '46.73-7', desc: 'Comércio atacadista de material elétrico', risk: '2' },
    { code: '46.74-5', desc: 'Comércio atacadista de cimento', risk: '3' },
    { code: '46.79-6', desc: 'Comércio atacadista especializado de materiais de construção não especificados anteriormente', risk: '2' },
    { code: '46.81-8', desc: 'Comércio atacadista de combustíveis sólidos, líquidos e gasosos, exceto gás natural e GLP', risk: '3' },
    { code: '46.82-6', desc: 'Comércio atacadista de gás liqüefeito de petróleo (GLP)', risk: '3' },
    { code: '46.83-4', desc: 'Comércio atacadista de defensivos agrícolas, adubos, fertilizantes e corretivos do solo', risk: '3' },
    { code: '46.84-2', desc: 'Comércio atacadista de produtos químicos e petroquímicos, exceto agroquímicos', risk: '3' },
    { code: '46.85-1', desc: 'Comércio atacadista de produtos siderúrgicos e metalúrgicos, exceto para construção', risk: '3' },
    { code: '46.86-9', desc: 'Comércio atacadista de papel e papelão em bruto e de embalagens', risk: '2' },
    { code: '46.87-7', desc: 'Comércio atacadista de resíduos e sucatas', risk: '3' },
    { code: '46.89-3', desc: 'Comércio atacadista especializado de outros produtos intermediários não especificados anteriormente', risk: '3' },
    { code: '46.91-5', desc: 'Comércio atacadista de mercadorias em geral, com predominância de produtos alimentícios', risk: '2' },
    { code: '46.92-3', desc: 'Comércio atacadista de mercadorias em geral, com predominância de insumos agropecuários', risk: '2' },
    { code: '46.93-1', desc: 'Comércio atacadista de mercadorias em geral, sem predominância de alimentos ou de insumos agropecuários', risk: '2' },
    { code: '47.11-3', desc: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - hipermercados e supermercados', risk: '2' },
    { code: '47.12-1', desc: 'Comércio varejista de mercadorias em geral, com predominância de produtos alimentícios - minimercados, mercearias e armazéns', risk: '1' },
    { code: '47.13-0', desc: 'Comércio varejista de mercadorias em geral, sem predominância de produtos alimentícios', risk: '1' },
    { code: '47.21-1', desc: 'Comércio varejista de produtos de padaria, laticínio, doces, balas e semelhantes', risk: '2' },
    { code: '47.22-9', desc: 'Comércio varejista de carnes e pescados - açougues e peixarias', risk: '2' },
    { code: '47.23-7', desc: 'Comércio varejista de bebidas', risk: '1' },
    { code: '47.24-5', desc: 'Comércio varejista de hortifrutigranjeiros', risk: '1' },
    { code: '47.29-6', desc: 'Comércio varejista de produtos alimentícios em geral ou especializado em produtos alimentícios não especificados anteriormente', risk: '1' },
    { code: '47.31-8', desc: 'Comércio varejista de combustíveis para veículos automotores', risk: '3' },
    { code: '47.32-6', desc: 'Comércio varejista de lubrificantes', risk: '3' },
    { code: '47.41-5', desc: 'Comércio varejista de tintas e materiais para pintura', risk: '2' },
    { code: '47.42-3', desc: 'Comércio varejista de material elétrico', risk: '1' },
    { code: '47.43-1', desc: 'Comércio varejista de vidros', risk: '2' },
    { code: '47.44-0', desc: 'Comércio varejista de ferragens, madeira e materiais de construção', risk: '2' },
    { code: '47.51-2', desc: 'Comércio varejista especializado de equipamentos e suprimentos de informática', risk: '1' },
    { code: '47.52-1', desc: 'Comércio varejista especializado de equipamentos de telefonia e comunicação', risk: '1' },
    { code: '47.53-9', desc: 'Comércio varejista especializado de eletrodomésticos e equipamentos de áudio e vídeo', risk: '1' },
    { code: '47.54-7', desc: 'Comércio varejista especializado de móveis, colchoaria e artigos de iluminação', risk: '1' },
    { code: '47.55-5', desc: 'Comércio varejista especializado de tecidos e artigos de cama, mesa e banho', risk: '1' },
    { code: '47.56-3', desc: 'Comércio varejista especializado de instrumentos musicais e acessórios', risk: '1' },
    { code: '47.57-1', desc: 'Comércio varejista especializado de peças e acessórios para aparelhos eletroeletrônicos para uso doméstico, exceto informática e comunicação', risk: '1' },
    { code: '47.59-8', desc: 'Comércio varejista de artigos de uso doméstico não especificados anteriormente', risk: '1' },
    { code: '47.61-0', desc: 'Comércio varejista de livros, jornais, revistas e papelaria', risk: '1' },
    { code: '47.62-8', desc: 'Comércio varejista de discos, CDs, DVDs e fitas', risk: '1' },
    { code: '47.63-6', desc: 'Comércio varejista de artigos recreativos e esportivos', risk: '1' },
    { code: '47.71-7', desc: 'Comércio varejista de produtos farmacêuticos para uso humano e veterinário', risk: '2' },
    { code: '47.72-5', desc: 'Comércio varejista de cosméticos, produtos de perfumaria e de higiene pessoal', risk: '1' },
    { code: '47.73-3', desc: 'Comércio varejista de artigos médicos e ortopédicos', risk: '1' },
    { code: '47.74-1', desc: 'Comércio varejista de artigos de óptica', risk: '1' },
    { code: '47.81-4', desc: 'Comércio varejista de artigos do vestuário e acessórios', risk: '1' },
    { code: '47.82-2', desc: 'Comércio varejista de calçados e artigos de viagem', risk: '1' },
    { code: '47.83-1', desc: 'Comércio varejista de jóias e relógios', risk: '1' },
    { code: '47.84-9', desc: 'Comércio varejista de gás liqüefeito de petróleo (GLP)', risk: '3' },
    { code: '47.85-7', desc: 'Comércio varejista de animais vivos e de artigos e alimentos para animais de estimação', risk: '1' },
    { code: '47.89-0', desc: 'Comércio varejista de outros produtos novos não especificados anteriormente', risk: '1' },
    { code: '47.90-3', desc: 'Comércio varejista fora de lojas, bancas ou feiras (Internet, Correio, etc.)', risk: '1' },
    { code: '49.11-6', desc: 'Transporte ferroviário de carga', risk: '3' },
    { code: '49.12-4', desc: 'Transporte metroferroviário de passageiros', risk: '3' },
    { code: '49.21-3', desc: 'Transporte rodoviário coletivo de passageiros, com itinerário fixo', risk: '3' },
    { code: '49.22-1', desc: 'Transporte rodoviário coletivo de passageiros, sob regime de fretamento', risk: '3' },
    { code: '49.23-0', desc: 'Transporte rodoviário de táxi', risk: '3' },
    { code: '49.24-8', desc: 'Transporte escolar', risk: '3' },
    { code: '49.29-9', desc: 'Transporte rodoviário coletivo de passageiros, sob regime de fretamento, e outros transportes rodoviários', risk: '3' },
    { code: '49.30-2', desc: 'Transporte rodoviário de carga', risk: '3' },
    { code: '49.40-0', desc: 'Transporte dutoviário', risk: '3' },
    { code: '49.50-7', desc: 'Trens turísticos, teleféricos e similares', risk: '3' },
    { code: '50.11-4', desc: 'Transporte marítimo de cabotagem', risk: '3' },
    { code: '50.12-2', desc: 'Transporte marítimo de longo curso', risk: '3' },
    { code: '50.21-1', desc: 'Transporte por navegação interior de carga', risk: '3' },
    { code: '50.22-0', desc: 'Transporte por navegação interior de passageiros', risk: '3' },
    { code: '50.30-1', desc: 'Navegação de apoio', risk: '3' },
    { code: '50.91-2', desc: 'Transporte por navegação de travessia', risk: '3' },
    { code: '50.99-8', desc: 'Transportes aquaviários não especificados anteriormente', risk: '3' },
    { code: '51.11-1', desc: 'Transporte aéreo de passageiros regular', risk: '3' },
    { code: '51.12-9', desc: 'Transporte aéreo de passageiros não-regular', risk: '3' },
    { code: '51.20-0', desc: 'Transporte aéreo de carga', risk: '3' },
    { code: '51.30-7', desc: 'Transporte espacial', risk: '3' },
    { code: '52.11-7', desc: 'Armazenamento', risk: '3' },
    { code: '52.12-5', desc: 'Carga e descarga', risk: '3' },
    { code: '52.21-4', desc: 'Concessionárias de rodovias, pontes, túneis e serviços relacionados', risk: '3' },
    { code: '52.22-2', desc: 'Terminais rodoviários e ferroviários', risk: '3' },
    { code: '52.23-1', desc: 'Estacionamento de veículos', risk: '3' },
    { code: '52.29-0', desc: 'Atividades auxiliares dos transportes terrestres não especificadas anteriormente', risk: '3' },
    { code: '52.31-1', desc: 'Gestão de portos e terminais', risk: '3' },
    { code: '52.32-0', desc: 'Atividades de agenciamento marítimo', risk: '3' },
    { code: '52.39-7', desc: 'Atividades auxiliares dos transportes aquaviários não especificadas anteriormente', risk: '3' },
    { code: '52.40-1', desc: 'Atividades auxiliares dos transportes aéreos', risk: '3' },
    { code: '52.50-8', desc: 'Atividades relacionadas à organização do transporte de carga', risk: '3' },
    { code: '53.10-5', desc: 'Atividades de correio', risk: '3' },
    { code: '53.20-2', desc: 'Atividades de malote e de entrega', risk: '3' },
    { code: '55.10-8', desc: 'Hotéis e similares', risk: '2' },
    { code: '55.90-6', desc: 'Outros tipos de alojamento não especificados anteriormente', risk: '2' },
    { code: '56.11-2', desc: 'Restaurantes e outros estabelecimentos de serviços de alimentação e bebidas', risk: '2' },
    { code: '56.12-1', desc: 'Serviços ambulantes de alimentação', risk: '2' },
    { code: '56.20-1', desc: 'Serviços de catering, bufê e outros serviços de comida preparada', risk: '2' },
    { code: '58.11-5', desc: 'Edição de livros', risk: '1' },
    { code: '58.12-3', desc: 'Edição de jornais', risk: '1' },
    { code: '58.13-1', desc: 'Edição de revistas', risk: '1' },
    { code: '58.21-2', desc: 'Edição de softwares', risk: '1' },
    { code: '59.11-1', desc: 'Atividades de produção cinematográfica, de vídeos e de programas de televisão', risk: '2' },
    { code: '59.12-0', desc: 'Atividades de pós-produção cinematográfica, de vídeos e de programas de televisão', risk: '2' },
    { code: '59.13-8', desc: 'Distribuição cinematográfica, de vídeo e de programas de televisão', risk: '1' },
    { code: '59.14-6', desc: 'Atividades de exibição cinematográfica', risk: '2' },
    { code: '60.10-1', desc: 'Atividades de rádio', risk: '2' },
    { code: '60.21-7', desc: 'Atividades de televisão aberta', risk: '2' },
    { code: '60.22-5', desc: 'Programadoras e atividades relacionadas à televisão por assinatura', risk: '2' },
    { code: '61.10-8', desc: 'Telecomunicações por fio', risk: '2' },
    { code: '61.20-5', desc: 'Telecomunicações sem fio', risk: '2' },
    { code: '61.30-2', desc: 'Telecomunicações por satélite', risk: '2' },
    { code: '61.41-8', desc: 'Operadoras de televisão por assinatura por cabo', risk: '2' },
    { code: '61.90-6', desc: 'Outras atividades de telecomunicações', risk: '2' },
    { code: '62.01-5', desc: 'Desenvolvimento de programas de computador sob encomenda', risk: '1' },
    { code: '62.02-3', desc: 'Desenvolvimento e licenciamento de programas de computador customizáveis', risk: '1' },
    { code: '62.03-1', desc: 'Desenvolvimento e licenciamento de programas de computador não-customizáveis', risk: '1' },
    { code: '62.04-0', desc: 'Consultoria em tecnologia da informação', risk: '1' },
    { code: '62.09-1', desc: 'Suporte técnico, manutenção e outros serviços em tecnologia da informação', risk: '1' },
    { code: '63.11-9', desc: 'Tratamento de dados, provedores de serviços de aplicação e serviços de hospedagem na internet', risk: '1' },
    { code: '63.19-4', desc: 'Portais, provedores de conteúdo e outros serviços de informação na internet', risk: '1' },
    { code: '63.91-7', desc: 'Agências de notícias', risk: '1' },
    { code: '64.10-7', desc: 'Banco Central', risk: '1' },
    { code: '64.21-2', desc: 'Bancos comerciais', risk: '1' },
    { code: '64.22-1', desc: 'Bancos múltiplos, com carteira comercial', risk: '1' },
    { code: '64.23-9', desc: 'Caixas econômicas', risk: '1' },
    { code: '64.24-7', desc: 'Crédito cooperativo', risk: '1' },
    { code: '64.31-0', desc: 'Intermediação financeira', risk: '1' },
    { code: '64.32-8', desc: 'Bancos de investimento', risk: '1' },
    { code: '64.33-6', desc: 'Bancos de desenvolvimento', risk: '1' },
    { code: '64.34-4', desc: 'Crédito imobiliário', risk: '1' },
    { code: '64.35-2', desc: 'Crédito, financiamento e investimento', risk: '1' },
    { code: '64.36-1', desc: 'Agências de fomento', risk: '1' },
    { code: '64.37-9', desc: 'Sociedades de crédito ao microempreendedor', risk: '1' },
    { code: '64.40-9', desc: 'Arrendamento mercantil', risk: '1' },
    { code: '64.50-6', desc: 'Sociedades de capitalização', risk: '1' },
    { code: '64.61-1', desc: 'Holdings de instituições financeiras', risk: '1' },
    { code: '64.62-0', desc: 'Holdings de instituições não-financeiras', risk: '1' },
    { code: '64.63-8', desc: 'Outras sociedades de participação, exceto holdings', risk: '1' },
    { code: '64.70-1', desc: 'Fundos de investimento', risk: '1' },
    { code: '64.91-3', desc: 'Securitização de créditos', risk: '1' },
    { code: '64.92-1', desc: 'Securitização de títulos e valores mobiliários', risk: '1' },
    { code: '64.93-0', desc: 'Administração de consórcios', risk: '1' },
    { code: '64.99-9', desc: 'Outras atividades de serviços financeiros', risk: '1' },
    { code: '65.11-1', desc: 'Seguros de vida', risk: '1' },
    { code: '65.12-0', desc: 'Seguros não-vida', risk: '1' },
    { code: '65.20-1', desc: 'Seguros-saúde', risk: '1' },
    { code: '65.30-8', desc: 'Resseguros', risk: '1' },
    { code: '65.41-3', desc: 'Previdência complementar fechada', risk: '1' },
    { code: '65.42-1', desc: 'Previdência complementar aberta', risk: '1' },
    { code: '65.50-2', desc: 'Planos de saúde', risk: '1' },
    { code: '66.11-8', desc: 'Administração de bolsas e mercados de balcão organizados', risk: '1' },
    { code: '66.12-6', desc: 'Atividades de intermediários em transações de títulos, valores mobiliários e mercadorias', risk: '1' },
    { code: '66.13-4', desc: 'Administração de cartões de crédito', risk: '1' },
    { code: '66.19-3', desc: 'Atividades auxiliares dos serviços financeiros não especificadas anteriormente', risk: '1' },
    { code: '66.21-5', desc: 'Avaliação de riscos e perdas', risk: '1' },
    { code: '66.22-3', desc: 'Corretores e agentes de seguros, de planos de previdência complementar e de saúde', risk: '1' },
    { code: '66.29-1', desc: 'Atividades auxiliares dos seguros, da previdência complementar e dos planos de saúde não especificadas anteriormente', risk: '1' },
    { code: '66.30-4', desc: 'Atividades de administração de fundos por contrato ou comissão', risk: '1' },
    { code: '68.10-2', desc: 'Atividades imobiliárias de imóveis próprios', risk: '1' },
    { code: '68.21-8', desc: 'Intermediação na compra, venda e aluguel de imóveis', risk: '1' },
    { code: '68.22-6', desc: 'Gestão e administração da propriedade imobiliária', risk: '1' },
    { code: '69.11-7', desc: 'Atividades jurídicas, exceto cartórios', risk: '1' },
    { code: '69.12-5', desc: 'Cartórios', risk: '1' },
    { code: '69.20-6', desc: 'Atividades de contabilidade, consultoria e auditoria contábil e tributária', risk: '1' },
    { code: '70.20-4', desc: 'Atividades de consultoria em gestão empresarial', risk: '1' },
    { code: '71.11-1', desc: 'Serviços de arquitetura', risk: '1' },
    { code: '71.12-0', desc: 'Serviços de engenharia', risk: '1' },
    { code: '71.19-7', desc: 'Atividades técnicas relacionadas à arquitetura e engenharia', risk: '1' },
    { code: '71.20-1', desc: 'Testes e análises técnicas', risk: '2' },
    { code: '72.10-0', desc: 'Pesquisa e desenvolvimento experimental em ciências físicas e naturais', risk: '2' },
    { code: '72.20-7', desc: 'Pesquisa e desenvolvimento experimental em ciências sociais e humanas', risk: '1' },
    { code: '73.11-4', desc: 'Agências de publicidade', risk: '1' },
    { code: '73.12-2', desc: 'Agenciamento de espaços para publicidade, exceto em veículos de comunicação', risk: '1' },
    { code: '73.19-0', desc: 'Atividades de publicidade não especificadas anteriormente', risk: '1' },
    { code: '73.20-3', desc: 'Pesquisas de mercado e de opinião pública', risk: '1' },
    { code: '74.10-2', desc: 'Design e decoração de interiores', risk: '1' },
    { code: '74.20-0', desc: 'Atividades fotográficas e similares', risk: '1' },
    { code: '74.90-1', desc: 'Atividades profissionais, científicas e técnicas não especificadas anteriormente', risk: '1' },
    { code: '75.00-1', desc: 'Atividades veterinárias', risk: '3' },
    { code: '77.11-0', desc: 'Locação de automóveis sem condutor', risk: '1' },
    { code: '77.19-5', desc: 'Locação de meios de transporte não especificados anteriormente, sem condutor', risk: '1' },
    { code: '77.21-7', desc: 'Aluguel de equipamentos recreativos e esportivos', risk: '1' },
    { code: '77.22-5', desc: 'Aluguel de fitas de vídeo, DVDs e similares', risk: '1' },
    { code: '77.23-3', desc: 'Aluguel de objetos do vestuário, jóias e acessórios', risk: '1' },
    { code: '77.29-2', desc: 'Aluguel de objetos pessoais e domésticos não especificados anteriormente', risk: '1' },
    { code: '77.31-4', desc: 'Aluguel de máquinas e equipamentos agrícolas sem operador', risk: '1' },
    { code: '77.32-2', desc: 'Aluguel de máquinas e equipamentos para construção sem operador', risk: '1' },
    { code: '77.33-1', desc: 'Aluguel de máquinas e equipamentos para escritório', risk: '1' },
    { code: '77.39-0', desc: 'Aluguel de máquinas e equipamentos não especificados anteriormente', risk: '1' },
    { code: '77.40-3', desc: 'Gestão de ativos intangíveis não-financeiros', risk: '1' },
    { code: '78.10-8', desc: 'Seleção e agenciamento de mão-de-obra', risk: '1' },
    { code: '78.20-5', desc: 'Locação de mão-de-obra temporária', risk: '1' },
    { code: '78.30-2', desc: 'Fornecimento e gestão de recursos humanos para terceiros', risk: '1' },
    { code: '79.11-2', desc: 'Agências de viagens', risk: '1' },
    { code: '79.12-1', desc: 'Operadores turísticos', risk: '1' },
    { code: '79.90-2', desc: 'Serviços de reservas e outros serviços de turismo não especificados anteriormente', risk: '1' },
    { code: '80.11-1', desc: 'Atividades de vigilância e segurança privada', risk: '3' },
    { code: '80.12-9', desc: 'Atividades de transporte de valores', risk: '3' },
    { code: '80.20-0', desc: 'Atividades de monitoramento de sistemas de segurança', risk: '3' },
    { code: '80.30-7', desc: 'Atividades de investigação particular', risk: '3' },
    { code: '81.11-7', desc: 'Serviços combinados para apoio a edifícios, exceto condomínios prediais', risk: '2' },
    { code: '81.12-5', desc: 'Condomínios prediais', risk: '2' },
    { code: '81.21-4', desc: 'Limpeza em prédios e em domicílios', risk: '3' },
    { code: '81.22-2', desc: 'Imunização e controle de pragas urbanas', risk: '3' },
    { code: '81.29-0', desc: 'Atividades de limpeza não especificadas anteriormente', risk: '3' },
    { code: '81.30-3', desc: 'Atividades paisagísticas', risk: '2' },
    { code: '82.11-3', desc: 'Serviços combinados de escritório e apoio administrativo', risk: '1' },
    { code: '82.19-9', desc: 'Fotocópias, preparação de documentos e outros serviços especializados de apoio administrativo', risk: '1' },
    { code: '82.20-2', desc: 'Atividades de teleatendimento', risk: '1' },
    { code: '82.30-0', desc: 'Atividades de organização de eventos, exceto culturais e esportivos', risk: '1' },
    { code: '82.91-1', desc: 'Atividades de cobrança e informações cadastrais', risk: '1' },
    { code: '82.92-0', desc: 'Envasamento e empacotamento sob contrato', risk: '2' },
    { code: '82.99-7', desc: 'Atividades de serviços prestados principalmente às empresas não especificadas anteriormente', risk: '1' },
    { code: '84.11-6', desc: 'Administração pública em geral', risk: '1' },
    { code: '84.12-4', desc: 'Regulação das atividades de saúde, educação, serviços culturais e outros serviços sociais', risk: '1' },
    { code: '84.13-2', desc: 'Regulação das atividades econômicas', risk: '1' },
    { code: '84.21-3', desc: 'Relações exteriores', risk: '1' },
    { code: '84.22-1', desc: 'Defesa', risk: '1' },
    { code: '84.23-0', desc: 'Justiça', risk: '1' },
    { code: '84.24-8', desc: 'Segurança e ordem pública', risk: '3' },
    { code: '84.25-6', desc: 'Defesa Civil', risk: '3' },
    { code: '84.30-2', desc: 'Seguridade social obrigatória', risk: '1' },
    { code: '85.11-2', desc: 'Educação infantil - creche', risk: '2' },
    { code: '85.12-1', desc: 'Educação infantil - pré-escola', risk: '2' },
    { code: '85.13-9', desc: 'Ensino fundamental', risk: '2' },
    { code: '85.20-1', desc: 'Ensino médio', risk: '2' },
    { code: '85.31-7', desc: 'Educação superior - graduação', risk: '2' },
    { code: '85.32-5', desc: 'Educação superior - graduação e pós-graduação', risk: '2' },
    { code: '85.33-3', desc: 'Educação superior - pós-graduação e extensão', risk: '2' },
    { code: '85.41-4', desc: 'Educação profissional de nível técnico', risk: '2' },
    { code: '85.42-2', desc: 'Educação profissional de nível tecnológico', risk: '2' },
    { code: '85.50-3', desc: 'Atividades de apoio à educação', risk: '2' },
    { code: '85.91-1', desc: 'Ensino de esportes', risk: '2' },
    { code: '85.92-9', desc: 'Ensino de arte e cultura', risk: '2' },
    { code: '85.93-7', desc: 'Ensino de idiomas', risk: '2' },
    { code: '85.99-6', desc: 'Outras atividades de ensino não especificadas anteriormente', risk: '2' },
    { code: '86.10-1', desc: 'Atividades de atendimento hospitalar', risk: '3' },
    { code: '86.21-6', desc: 'Serviços móveis de atendimento a urgências', risk: '3' },
    { code: '86.22-4', desc: 'Serviços de remoção de pacientes, exceto os serviços móveis de atendimento a urgências', risk: '3' },
    { code: '86.30-5', desc: 'Atividades de atenção ambulatorial executadas por médicos e odontólogos', risk: '2' },
    { code: '86.40-2', desc: 'Atividades de serviços de complementação diagnóstica e terapêutica', risk: '3' },
    { code: '86.50-0', desc: 'Atividades de profissionais da área de saúde, exceto médicos e odontólogos', risk: '2' },
    { code: '86.60-7', desc: 'Atividades de apoio à gestão de saúde', risk: '1' },
    { code: '86.90-9', desc: 'Atividades de atenção à saúde humana não especificadas anteriormente', risk: '2' },
    { code: '87.11-5', desc: 'Clínicas e residências geriátricas', risk: '2' },
    { code: '87.12-3', desc: 'Atividades de fornecimento de infra-estrutura de apoio e assistência a paciente em domicílio', risk: '2' },
    { code: '87.20-4', desc: 'Atividades de assistência psicossocial e à saúde a portadores de distúrbios psíquicos, deficiência mental e dependência química', risk: '2' },
    { code: '87.30-1', desc: 'Atividades de assistência social prestadas em residências coletivas e particulares', risk: '2' },
    { code: '88.00-6', desc: 'Serviços de assistência social sem alojamento', risk: '2' },
    { code: '90.01-9', desc: 'Artes cênicas, espetáculos e atividades complementares', risk: '2' },
    { code: '90.02-7', desc: 'Criação artística', risk: '1' },
    { code: '90.03-5', desc: 'Gestão de espaços para artes cênicas, espetáculos e outras atividades artísticas', risk: '2' },
    { code: '91.01-5', desc: 'Atividades de bibliotecas e arquivos', risk: '1' },
    { code: '91.02-3', desc: 'Atividades de museus e de exploração de lugares e prédios históricos e atrações similares', risk: '1' },
    { code: '91.03-1', desc: 'Atividades de jardins botânicos, zoológicos, parques nacionais e reservas ecológicas', risk: '2' },
    { code: '92.00-3', desc: 'Atividades de exploração de jogos de azar e apostas', risk: '1' },
    { code: '93.11-5', desc: 'Gestão de instalações de esportes', risk: '2' },
    { code: '93.12-3', desc: 'Clubes sociais, esportivos e similares', risk: '2' },
    { code: '93.13-1', desc: 'Atividades de condicionamento físico', risk: '2' },
    { code: '93.19-1', desc: 'Outras atividades esportivas', risk: '2' },
    { code: '93.21-2', desc: 'Parques de diversão e parques temáticos', risk: '2' },
    { code: '93.29-8', desc: 'Outras atividades de recreação e lazer', risk: '2' },
    { code: '94.11-1', desc: 'Atividades de organizações associativas patronais e empresariais', risk: '1' },
    { code: '94.12-0', desc: 'Atividades de organizações associativas profissionais', risk: '1' },
    { code: '94.20-1', desc: 'Atividades de organizações sindicais', risk: '1' },
    { code: '94.30-8', desc: 'Atividades de associações de defesa de direitos sociais', risk: '1' },
    { code: '94.91-0', desc: 'Atividades de organizações religiosas', risk: '1' },
    { code: '94.92-8', desc: 'Atividades de organizações políticas', risk: '1' },
    { code: '94.93-6', desc: 'Atividades de organizações associativas ligadas à cultura e à arte', risk: '1' },
    { code: '94.99-5', desc: 'Atividades associativas não especificadas anteriormente', risk: '1' },
    { code: '95.11-8', desc: 'Reparação e manutenção de computadores e de equipamentos periféricos', risk: '3' },
    { code: '95.12-6', desc: 'Reparação e manutenção de equipamentos de comunicação', risk: '3' },
    { code: '95.21-5', desc: 'Reparação e manutenção de equipamentos eletroeletrônicos de uso pessoal e doméstico', risk: '3' },
    { code: '95.29-1', desc: 'Reparação e manutenção de objetos e equipamentos pessoais e domésticos não especificados anteriormente', risk: '3' },
    { code: '96.01-7', desc: 'Lavanderias, tinturarias e toalheiros', risk: '2' },
    { code: '96.02-5', desc: 'Cabeleireiros e outras atividades de tratamento de beleza', risk: '2' },
    { code: '96.03-3', desc: 'Atividades funerárias e serviços relacionados', risk: '3' },
    { code: '96.09-2', desc: 'Atividades de serviços pessoais não especificadas anteriormente', risk: '2' },
    { code: '97.00-5', desc: 'Serviços domésticos', risk: '2' },
    { code: '99.00-8', desc: 'Organismos internacionais e outras instituições extraterritoriais', risk: '1' }
];